import {
  Send,
  Receipt,
  Download,
  RefreshCw,
  CreditCard,
  ArrowDownLeft,
  ShoppingBag,
  Tv,
  Coffee,
  Briefcase,
  TrendingUp,
  type LucideIcon,
  UtensilsCrossed,
  Car,
  Zap,
  Home,
  Plane,
  Smartphone,
  ShieldCheck,
  Building2,
  Repeat,
} from "lucide-react";

// ─── RICH TRANSACTION DATA MODEL ──────────────────────────────────────────────

export type TransactionDirection = "credit" | "debit";
export type TransactionStatus = "completed" | "pending" | "failed" | "processing";
export type TransactionType =
  | "shopping"
  | "subscription"
  | "food"
  | "salary"
  | "transfer"
  | "utilities"
  | "travel"
  | "transport"
  | "insurance"
  | "investment"
  | "refund"
  | "other";

export interface RichTransaction {
  id: string;
  merchant: string;
  merchantInitials: string;
  merchantColor: string;
  description: string;
  amount: number;
  direction: TransactionDirection;
  runningBalance: number;
  date: string;
  time: string;
  dateISO: string;
  status: TransactionStatus;
  type: TransactionType;
  category: string;
  icon: LucideIcon;
  referenceNumber: string;
  transactionId: string;
  paymentMethod: string;
  accountUsed: string;
  fees: number;
  exchangeRate?: string;
  notes?: string;
  statusTimeline: Array<{
    label: string;
    time: string;
    done: boolean;
  }>;
  balanceBefore?: number;
  balanceAfter?: number;
  source?: string;
  destination?: string;
  recipientName?: string;
  recipientBank?: string;
  recipientAccountNumber?: string;
  destinationCountry?: string;
  transferSpeed?: string;
  createdBy?: string;
  approvedBy?: string;
}

// ─── MOCK RICH TRANSACTIONS ────────────────────────────────────────────────────

export const MOCK_RICH_TRANSACTIONS: RichTransaction[] = [
  {
    id: "rtx-001",
    merchant: "Employer Monthly Payroll",
    merchantInitials: "EP",
    merchantColor: "#16A34A",
    description: "Monthly salary deposit — August 2026",
    amount: 4850.00,
    direction: "credit",
    runningBalance: 12450.80,
    date: "Aug 04, 2026",
    time: "8:00 AM",
    dateISO: "2026-08-04T08:00:00",
    status: "completed",
    type: "salary",
    category: "Income",
    icon: Briefcase,
    referenceNumber: "REF-2026-08-001",
    transactionId: "TXN-FC-0048821",
    paymentMethod: "ACH Direct Deposit",
    accountUsed: "Primary Checking •••• 8421",
    fees: 0,
    notes: "Monthly salary — August cycle. Received on schedule.",
    statusTimeline: [
      { label: "Initiated by employer", time: "Aug 04, 8:00 AM", done: true },
      { label: "ACH network routed", time: "Aug 04, 8:02 AM", done: true },
      { label: "Settled to account", time: "Aug 04, 8:05 AM", done: true },
    ],
  },
  {
    id: "rtx-002",
    merchant: "Amazon Prime Subscription",
    merchantInitials: "AM",
    merchantColor: "#FF9900",
    description: "Monthly Prime membership renewal",
    amount: -14.99,
    direction: "debit",
    runningBalance: 7600.80,
    date: "Aug 04, 2026",
    time: "10:12 AM",
    dateISO: "2026-08-04T10:12:00",
    status: "completed",
    type: "subscription",
    category: "Subscriptions",
    icon: Tv,
    referenceNumber: "REF-2026-08-002",
    transactionId: "TXN-FC-0048822",
    paymentMethod: "FINACORM Debit Card •••• 4821",
    accountUsed: "Primary Checking •••• 8421",
    fees: 0,
    statusTimeline: [
      { label: "Card authorised", time: "Aug 04, 10:12 AM", done: true },
      { label: "Payment processed", time: "Aug 04, 10:12 AM", done: true },
      { label: "Receipt issued", time: "Aug 04, 10:13 AM", done: true },
    ],
  },
  {
    id: "rtx-003",
    merchant: "Starbucks Coffee",
    merchantInitials: "SB",
    merchantColor: "#00704A",
    description: "Iced Americano × 2 + pastry",
    amount: -6.45,
    direction: "debit",
    runningBalance: 7585.81,
    date: "Aug 03, 2026",
    time: "3:30 PM",
    dateISO: "2026-08-03T15:30:00",
    status: "completed",
    type: "food",
    category: "Food & Drink",
    icon: Coffee,
    referenceNumber: "REF-2026-08-003",
    transactionId: "TXN-FC-0048810",
    paymentMethod: "FINACORM Debit Card •••• 4821",
    accountUsed: "Primary Checking •••• 8421",
    fees: 0,
    statusTimeline: [
      { label: "Card tapped at POS", time: "Aug 03, 3:30 PM", done: true },
      { label: "Merchant approved", time: "Aug 03, 3:30 PM", done: true },
      { label: "Settled", time: "Aug 03, 3:31 PM", done: true },
    ],
  },
  {
    id: "rtx-004",
    merchant: "Apple Store",
    merchantInitials: "AS",
    merchantColor: "#555555",
    description: "MacBook Pro 14-inch M4 — Space Black",
    amount: -1299.00,
    direction: "debit",
    runningBalance: 7579.36,
    date: "Jul 31, 2026",
    time: "2:45 PM",
    dateISO: "2026-07-31T14:45:00",
    status: "completed",
    type: "shopping",
    category: "Electronics",
    icon: ShoppingBag,
    referenceNumber: "REF-2026-07-921",
    transactionId: "TXN-FC-0047991",
    paymentMethod: "FINACORM Metal Debit •••• 4821",
    accountUsed: "Primary Checking •••• 8421",
    fees: 0,
    notes: "Purchase receipt emailed to n.o@finacorm.bank",
    statusTimeline: [
      { label: "Payment authorised", time: "Jul 31, 2:45 PM", done: true },
      { label: "Apple confirmed order", time: "Jul 31, 2:46 PM", done: true },
      { label: "Funds cleared", time: "Aug 01, 8:00 AM", done: true },
    ],
  },
  {
    id: "rtx-005",
    merchant: "Wire Transfer → Sarah Jenkins",
    merchantInitials: "SJ",
    merchantColor: "#2563EB",
    description: "Personal wire to Sarah Jenkins — Rent share",
    amount: -250.00,
    direction: "debit",
    runningBalance: 8878.36,
    date: "Jul 29, 2026",
    time: "11:00 AM",
    dateISO: "2026-07-29T11:00:00",
    status: "completed",
    type: "transfer",
    category: "Transfers",
    icon: Send,
    referenceNumber: "REF-2026-07-887",
    transactionId: "TXN-FC-0047815",
    paymentMethod: "Internal Bank Wire",
    accountUsed: "Primary Checking •••• 8421",
    fees: 0.50,
    statusTimeline: [
      { label: "Wire instruction submitted", time: "Jul 29, 11:00 AM", done: true },
      { label: "Compliance verified", time: "Jul 29, 11:02 AM", done: true },
      { label: "Delivered to recipient", time: "Jul 29, 11:05 AM", done: true },
    ],
  },
  {
    id: "rtx-006",
    merchant: "Target Supercenter",
    merchantInitials: "TG",
    merchantColor: "#CC0000",
    description: "Household supplies — weekly grocery run",
    amount: -84.20,
    direction: "debit",
    runningBalance: 9128.36,
    date: "Jul 28, 2026",
    time: "5:10 PM",
    dateISO: "2026-07-28T17:10:00",
    status: "completed",
    type: "shopping",
    category: "Groceries",
    icon: ShoppingBag,
    referenceNumber: "REF-2026-07-840",
    transactionId: "TXN-FC-0047755",
    paymentMethod: "FINACORM Debit Card •••• 4821",
    accountUsed: "Primary Checking •••• 8421",
    fees: 0,
    statusTimeline: [
      { label: "Card authorised at POS", time: "Jul 28, 5:10 PM", done: true },
      { label: "Payment cleared", time: "Jul 28, 5:10 PM", done: true },
      { label: "Settled", time: "Jul 29, 8:00 AM", done: true },
    ],
  },
  {
    id: "rtx-007",
    merchant: "Netflix",
    merchantInitials: "NF",
    merchantColor: "#E50914",
    description: "Netflix Standard HD plan — August renewal",
    amount: -15.49,
    direction: "debit",
    runningBalance: 9212.56,
    date: "Jul 26, 2026",
    time: "12:00 AM",
    dateISO: "2026-07-26T00:00:00",
    status: "completed",
    type: "subscription",
    category: "Subscriptions",
    icon: Tv,
    referenceNumber: "REF-2026-07-800",
    transactionId: "TXN-FC-0047699",
    paymentMethod: "FINACORM Debit Card •••• 4821",
    accountUsed: "Primary Checking •••• 8421",
    fees: 0,
    statusTimeline: [
      { label: "Auto-renewal triggered", time: "Jul 26, 12:00 AM", done: true },
      { label: "Card charged", time: "Jul 26, 12:01 AM", done: true },
      { label: "Subscription extended", time: "Jul 26, 12:01 AM", done: true },
    ],
  },
  {
    id: "rtx-008",
    merchant: "Uber Eats",
    merchantInitials: "UE",
    merchantColor: "#142328",
    description: "Sushi Roku delivery — 2-person order",
    amount: -42.80,
    direction: "debit",
    runningBalance: 9228.05,
    date: "Jul 25, 2026",
    time: "7:20 PM",
    dateISO: "2026-07-25T19:20:00",
    status: "completed",
    type: "food",
    category: "Food Delivery",
    icon: UtensilsCrossed,
    referenceNumber: "REF-2026-07-779",
    transactionId: "TXN-FC-0047640",
    paymentMethod: "FINACORM Debit Card •••• 4821",
    accountUsed: "Primary Checking •••• 8421",
    fees: 2.99,
    statusTimeline: [
      { label: "Order placed", time: "Jul 25, 7:20 PM", done: true },
      { label: "Payment authorised", time: "Jul 25, 7:21 PM", done: true },
      { label: "Delivery confirmed", time: "Jul 25, 8:04 PM", done: true },
    ],
  },
  {
    id: "rtx-009",
    merchant: "Revolut Wallet Top-up",
    merchantInitials: "RV",
    merchantColor: "#6366F1",
    description: "Top-up to Revolut travel wallet",
    amount: -100.00,
    direction: "debit",
    runningBalance: 9270.85,
    date: "Jul 23, 2026",
    time: "9:05 AM",
    dateISO: "2026-07-23T09:05:00",
    status: "failed",
    type: "transfer",
    category: "Transfers",
    icon: RefreshCw,
    referenceNumber: "REF-2026-07-711",
    transactionId: "TXN-FC-0047580",
    paymentMethod: "Internal Wire",
    accountUsed: "Primary Checking •••• 8421",
    fees: 0,
    notes: "Transaction declined by recipient institution. Funds returned within 2 business days.",
    statusTimeline: [
      { label: "Transfer initiated", time: "Jul 23, 9:05 AM", done: true },
      { label: "Routing attempted", time: "Jul 23, 9:06 AM", done: true },
      { label: "Declined by Revolut", time: "Jul 23, 9:07 AM", done: true },
      { label: "Funds returned", time: "Jul 25, 8:00 AM", done: false },
    ],
  },
  {
    id: "rtx-010",
    merchant: "Dividend Interest Credit",
    merchantInitials: "DI",
    merchantColor: "#0F766E",
    description: "Quarterly dividend payout — July 2026",
    amount: 12.15,
    direction: "credit",
    runningBalance: 9370.85,
    date: "Jul 21, 2026",
    time: "8:00 AM",
    dateISO: "2026-07-21T08:00:00",
    status: "completed",
    type: "investment",
    category: "Investment Returns",
    icon: TrendingUp,
    referenceNumber: "REF-2026-07-654",
    transactionId: "TXN-FC-0047500",
    paymentMethod: "Automatic Credit",
    accountUsed: "Primary Checking •••• 8421",
    fees: 0,
    statusTimeline: [
      { label: "Dividend calculated", time: "Jul 21, 8:00 AM", done: true },
      { label: "Credit posted", time: "Jul 21, 8:00 AM", done: true },
    ],
  },
  {
    id: "rtx-011",
    merchant: "London City Airport",
    merchantInitials: "LA",
    merchantColor: "#1E3A5F",
    description: "Return flight LCY → JFK — Business Class",
    amount: -520.00,
    direction: "debit",
    runningBalance: 9358.70,
    date: "Jul 19, 2026",
    time: "4:00 PM",
    dateISO: "2026-07-19T16:00:00",
    status: "completed",
    type: "travel",
    category: "Travel",
    icon: Plane,
    referenceNumber: "REF-2026-07-601",
    transactionId: "TXN-FC-0047420",
    paymentMethod: "FINACORM Metal Debit •••• 4821",
    accountUsed: "Primary Checking •••• 8421",
    fees: 0,
    exchangeRate: "USD — No conversion",
    statusTimeline: [
      { label: "Booking confirmed", time: "Jul 19, 4:00 PM", done: true },
      { label: "Card charged", time: "Jul 19, 4:01 PM", done: true },
      { label: "E-ticket issued", time: "Jul 19, 4:02 PM", done: true },
    ],
  },
  {
    id: "rtx-012",
    merchant: "National Grid — Electricity",
    merchantInitials: "NG",
    merchantColor: "#F59E0B",
    description: "Monthly electricity bill — July 2026",
    amount: -84.10,
    direction: "debit",
    runningBalance: 9878.70,
    date: "Jul 15, 2026",
    time: "9:00 AM",
    dateISO: "2026-07-15T09:00:00",
    status: "completed",
    type: "utilities",
    category: "Utilities",
    icon: Zap,
    referenceNumber: "REF-2026-07-511",
    transactionId: "TXN-FC-0047310",
    paymentMethod: "Standing Order",
    accountUsed: "Primary Checking •••• 8421",
    fees: 0,
    statusTimeline: [
      { label: "Standing order triggered", time: "Jul 15, 9:00 AM", done: true },
      { label: "Payment sent", time: "Jul 15, 9:01 AM", done: true },
      { label: "Utility confirmed", time: "Jul 15, 10:00 AM", done: true },
    ],
  },
  {
    id: "rtx-013",
    merchant: "Uber Technologies",
    merchantInitials: "UB",
    merchantColor: "#000000",
    description: "Ride — Shoreditch to London Bridge",
    amount: -18.50,
    direction: "debit",
    runningBalance: 9962.80,
    date: "Jul 14, 2026",
    time: "6:45 PM",
    dateISO: "2026-07-14T18:45:00",
    status: "completed",
    type: "transport",
    category: "Transport",
    icon: Car,
    referenceNumber: "REF-2026-07-488",
    transactionId: "TXN-FC-0047270",
    paymentMethod: "FINACORM Debit Card •••• 4821",
    accountUsed: "Primary Checking •••• 8421",
    fees: 0,
    statusTimeline: [
      { label: "Ride completed", time: "Jul 14, 6:44 PM", done: true },
      { label: "Receipt generated", time: "Jul 14, 6:45 PM", done: true },
      { label: "Payment processed", time: "Jul 14, 6:45 PM", done: true },
    ],
  },
  {
    id: "rtx-014",
    merchant: "Apple Store — Refund",
    merchantInitials: "AR",
    merchantColor: "#34C759",
    description: "Refund: Apple Lightning Cable (faulty)",
    amount: 29.00,
    direction: "credit",
    runningBalance: 9981.30,
    date: "Jul 12, 2026",
    time: "11:30 AM",
    dateISO: "2026-07-12T11:30:00",
    status: "completed",
    type: "refund",
    category: "Refunds",
    icon: ArrowDownLeft,
    referenceNumber: "REF-2026-07-410",
    transactionId: "TXN-FC-0047180",
    paymentMethod: "Refund to Debit Card",
    accountUsed: "Primary Checking •••• 8421",
    fees: 0,
    statusTimeline: [
      { label: "Return accepted by Apple", time: "Jul 12, 11:30 AM", done: true },
      { label: "Refund issued", time: "Jul 12, 11:32 AM", done: true },
      { label: "Credit posted to account", time: "Jul 13, 8:00 AM", done: true },
    ],
  },
  {
    id: "rtx-015",
    merchant: "T-Mobile Family Plan",
    merchantInitials: "TM",
    merchantColor: "#E4003A",
    description: "Family mobile plan — July billing cycle",
    amount: -45.00,
    direction: "debit",
    runningBalance: 9952.30,
    date: "Jul 10, 2026",
    time: "12:00 AM",
    dateISO: "2026-07-10T00:00:00",
    status: "pending",
    type: "subscription",
    category: "Subscriptions",
    icon: Smartphone,
    referenceNumber: "REF-2026-07-390",
    transactionId: "TXN-FC-0047100",
    paymentMethod: "Standing Order",
    accountUsed: "Primary Checking •••• 8421",
    fees: 0,
    notes: "Payment in processing — typically clears within 1 business day.",
    statusTimeline: [
      { label: "Auto-debit initiated", time: "Jul 10, 12:00 AM", done: true },
      { label: "Sent to T-Mobile", time: "Jul 10, 12:01 AM", done: true },
      { label: "Awaiting confirmation", time: "Pending", done: false },
    ],
  },
];
